
const Suggestions=({name})=>{
    console.log(name.slice(-5,-4))

    const data=[
        {disease:"Leaf Spot Disease",control:"Jackfruit leaf spot disease, also known as jackfruit leaf blight, is a fungal infection that affects the leaves of jackfruit trees (Artocarpus heterophyllus). It is caused by the fungus Phyllosticta artocarpina.Symptoms:Circular to irregular-shaped spots on the leaves.,Spots may start as small, water-soaked lesions and gradually enlarge.,The spots may have a dark brown or black center with a yellow or brown margin.,Infected leaves may turn yellow and eventually drop prematurely., Severely infected trees may show stunted growth and reduced fruit production."},
        {disease:"Leaf Spot Disease",control:"Jackfruit leaf spot disease, also known as jackfruit leaf blight, is a fungal infection that affects the leaves of jackfruit trees (Artocarpus heterophyllus). It is caused by the fungus Phyllosticta artocarpina.Symptoms:Circular to irregular-shaped spots on the leaves.,Spots may start as small, water-soaked lesions and gradually enlarge.,The spots may have a dark brown or black center with a yellow or brown margin.,Infected leaves may turn yellow and eventually drop prematurely., Severely infected trees may show stunted growth and reduced fruit production."},
        {disease:"Leaf Spot Disease",control:"Jackfruit leaf spot disease, also known as jackfruit leaf blight, is a fungal infection that affects the leaves of jackfruit trees (Artocarpus heterophyllus). It is caused by the fungus Phyllosticta artocarpina.Symptoms:Circular to irregular-shaped spots on the leaves.,Spots may start as small, water-soaked lesions and gradually enlarge.,The spots may have a dark brown or black center with a yellow or brown margin.,Infected leaves may turn yellow and eventually drop prematurely., Severely infected trees may show stunted growth and reduced fruit production."},
        {disease:"Leaf Spot Disease",control:"Jackfruit leaf spot disease, also known as jackfruit leaf blight, is a fungal infection that affects the leaves of jackfruit trees (Artocarpus heterophyllus). It is caused by the fungus Phyllosticta artocarpina.Symptoms:Circular to irregular-shaped spots on the leaves.,Spots may start as small, water-soaked lesions and gradually enlarge.,The spots may have a dark brown or black center with a yellow or brown margin.,Infected leaves may turn yellow and eventually drop prematurely., Severely infected trees may show stunted growth and reduced fruit production."},
        {disease:"No Disease",control:"Healthy leaf"},
        {disease:"No Disease",control:"Healthy leaf"},
        {disease:"No Disease",control:"Healthy fruit"},
        {disease:"No Disease",control:"Healthy fruit"},
        {disease:"Rhizopusrot",control:"Rhizopus rot is a common post-harvest disease that affects jackfruit and is caused by the fungus Rhizopus spp. The disease typically occurs during storage or transportation when the fruit is damaged or bruised, providing an entry point for the fungus.Symptoms of Rhizopus rot in jackfruit include:,Soft, watery areas on the fruit's surface.,The appearance of white or grayish cottony mycelium, which may later turn black.,The affected areas rapidly expand and become covered with black spore masses.Rhizopus rot is favored by warm and humid conditions, as well as poor air circulation. It can spread rapidly to adjacent fruits, leading to significant losses if not controlled."},
        {disease:"Rhizopusrot",control:"Rhizopus rot is a common post-harvest disease that affects jackfruit and is caused by the fungus Rhizopus spp. The disease typically occurs during storage or transportation when the fruit is damaged or bruised, providing an entry point for the fungus.Symptoms of Rhizopus rot in jackfruit include:,Soft, watery areas on the fruit's surface.,The appearance of white or grayish cottony mycelium, which may later turn black.,The affected areas rapidly expand and become covered with black spore masses.Rhizopus rot is favored by warm and humid conditions, as well as poor air circulation. It can spread rapidly to adjacent fruits, leading to significant losses if not controlled."},
        {disease:"Rhizopusrot",control:"Rhizopus rot is a common post-harvest disease that affects jackfruit and is caused by the fungus Rhizopus spp. The disease typically occurs during storage or transportation when the fruit is damaged or bruised, providing an entry point for the fungus.Symptoms of Rhizopus rot in jackfruit include:,Soft, watery areas on the fruit's surface.,The appearance of white or grayish cottony mycelium, which may later turn black.,The affected areas rapidly expand and become covered with black spore masses.Rhizopus rot is favored by warm and humid conditions, as well as poor air circulation. It can spread rapidly to adjacent fruits, leading to significant losses if not controlled."},
        {disease:"Rhizopusrot",control:"Rhizopus rot is a common post-harvest disease that affects jackfruit and is caused by the fungus Rhizopus spp. The disease typically occurs during storage or transportation when the fruit is damaged or bruised, providing an entry point for the fungus.Symptoms of Rhizopus rot in jackfruit include:,Soft, watery areas on the fruit's surface.,The appearance of white or grayish cottony mycelium, which may later turn black.,The affected areas rapidly expand and become covered with black spore masses.Rhizopus rot is favored by warm and humid conditions, as well as poor air circulation. It can spread rapidly to adjacent fruits, leading to significant losses if not controlled."},
    ]
return(
<div class="card w-96 bg-primary-content shadow-xl">
  <div class="card-body text-black">
    <h2 class="card-title ">{data[name.slice(-5,-4)].disease}</h2>
    <p>{data[name.slice(-5,-4)].control}</p>
  </div>
</div>
);
}

export default Suggestions